SandboxVars = {
    VERSION = 4,
    -- 修改此项设置"人口倍数"高级选项。默认=正常
    -- 1 = 疯狂
    -- 2 = 非常高
    -- 3 = 高
    -- 4 = 正常
    -- 5 = 低
    Zombies = 4,
    -- 默认=城市集中
    -- 1 = 城市集中
    Distribution = 1,
    -- 默认=1小时
    -- 1 = 15分钟
    -- 2 = 30分钟
    -- 3 = 1小时
    -- 4 = 2小时
    -- 5 = 3小时
    -- 6 = 4小时
    -- 7 = 5小时
    -- 8 = 6小时
    -- 9 = 7小时
    -- 10 = 8小时
    -- 11 = 9小时
    -- 12 = 10小时
    -- 13 = 11小时
    -- 14 = 12小时
    -- 15 = 13小时
    -- 16 = 14小时
    -- 17 = 15小时
    -- 18 = 16小时
    -- 19 = 17小时
    -- 20 = 18小时
    -- 21 = 19小时
    -- 22 = 20小时
    -- 23 = 21小时
    -- 24 = 22小时
    -- 25 = 23小时
    DayLength = 3,
    StartYear = 1,
    -- 默认=7月
    -- 1 = 1月
    -- 2 = 2月
    -- 3 = 3月
    -- 4 = 4月
    -- 5 = 5月
    -- 6 = 6月
    -- 7 = 7月
    -- 8 = 8月
    -- 9 = 9月
    -- 10 = 10月
    -- 11 = 11月
    StartMonth = 7,
    StartDay = 9,
    -- 默认=上午9点
    -- 1 = 上午7点
    -- 2 = 上午9点
    -- 3 = 中午12点
    -- 4 = 下午2点
    -- 5 = 下午5点
    -- 6 = 晚上9点
    -- 7 = 凌晨12点
    -- 8 = 凌晨2点
    StartTime = 2,
    -- 默认=0-30天
    -- 1 = 立即
    -- 2 = 0-30天
    -- 3 = 0-2个月
    -- 4 = 0-6个月
    -- 5 = 0-1年
    -- 6 = 0-5年
    -- 7 = 2-6个月
    WaterShut = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    ElecShut = 14,
    -- 最小值=-1 最大值=2147483647 默认=14
    WaterShutModifier = 14,
    -- 最小值=-1 最大值=2147483647 默认=14
    ElecShutModifier = 14,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    FoodLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    CannedFoodLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    LiteratureLoot = 3,
    -- 种子, 钉子, 锯子, 钓鱼竿, 各种工具等... 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    SurvivalGearsLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    MedicalLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    WeaponLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    RangedWeaponLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    AmmoLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    MechanicsLoot = 3,
    -- 默认=稀有
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 正常
    -- 4 = 常见
    OtherLoot = 3,
    -- 控制全局温度。默认=正常
    -- 1 = 非常冷
    -- 2 = 冷
    -- 3 = 正常
    -- 4 = 热
    Temperature = 3,
    -- 控制降雨频率。默认=正常
    -- 1 = 非常干燥
    -- 2 = 干燥
    -- 3 = 正常
    -- 4 = 多雨
    Rain = 2,
    -- 天数直到100%生长。默认=正常（100天）
    -- 1 = 非常快（20天）
    -- 2 = 快（50天）
    -- 3 = 正常（100天）
    -- 4 = 慢（200天）
    ErosionSpeed = 3,
    -- 天数直到100%生长。-1表示不生长。0表示使用Erosion Speed选项。最大36,500（100年）。最小值=-1最大值=36500默认=0
    ErosionDays = 0,
    -- 修改基础XP奖励动作的倍数。最小值=0.00最大值=1000.00默认=1.00
    XpMultiplier = 1.0,
    -- 使用此倍数乘以或减少引擎的总体音量。最小值=0.00最大值=100.00默认=1.00
    ZombieAttractionMultiplier = 1.0,
    -- 控制汽车是否被锁定、需要钥匙启动等。
    VehicleEasyUse = false,
    -- 控制植物生长速度。默认=正常
    -- 1 = 非常快
    -- 2 = 快
    -- 3 = 正常
    -- 4 = 慢
    Farming = 4,
    -- 控制食物在堆肥中分解的时间。默认=2周
    -- 1 = 1周
    -- 2 = 2周
    -- 3 = 3周
    -- 4 = 4周
    -- 5 = 6周
    -- 6 = 8周
    -- 7 = 10周
    CompostTime = 2,
    -- 控制角色饥饿、口渴和疲劳减少的速度。默认=正常
    -- 1 = 非常快
    -- 2 = 快
    -- 3 = 正常
    -- 4 = 慢
    StatsDecrease = 3,
    -- 控制鱼类和一般食物的丰富程度。默认=正常
    -- 1 = 非常贫瘠
    -- 2 = 贫瘠
    -- 3 = 正常
    -- 4 = 丰富
    NatureAbundance = 3,
    -- 默认=有时
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    Alarm = 3,
    -- 房屋和建筑被发现锁定的频率。默认=非常频繁
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    LockedHouses = 4,
    -- 携带芯片、水壶、书包、棒球棒和锤子。
    StarterKit = false,
    -- 食物的营养价值影响玩家的健康。
    Nutrition = true,
    -- 定义食物在冰箱内外腐烂的速度。默认=正常
    -- 1 = 非常快
    -- 2 = 快
    -- 3 = 正常
    -- 4 = 慢
    FoodRotSpeed = 3,
    -- 定义冰箱的有效性。默认=正常
    -- 1 = 非常低
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    FridgeFactor = 3,
    -- 物品将在已经搜刮过的容器中重新生成。物品不会在玩家制作的容器中重新生成。默认=无
    -- 1 = 无
    -- 2 = 每天
    -- 3 = 每周
    -- 4 = 每月
    LootRespawn = 4,
    -- 当>0时，物品不会在已访问过的区域重新生成。最小值=0 最大值=2147483647 默认=0
    SeenHoursPreventLootRespawn = 0,
    -- 一个逗号分隔的物品类型列表，将在HoursForWorldItemRemoval小时后被删除。
    WorldItemRemovalList = "Base.Vest,Base.Shirt,Base.Blouse,Base.Skirt,Base.Shoes,Base.Hat,Base.Glasses",
    -- 物品从掉落到地面到被删除的时间。物品将在下次加载地图的相应部分时被删除。最小值=0.00最大值=2147483647.00默认=24.00
    HoursForWorldItemRemoval = 24.0,
    -- 如果为真，任何不在WorldItemRemovalList中的物品将被删除。
    ItemRemovalListBlacklistToggle = false,
    -- 这将影响世界初始腐烂和食物腐烂。默认=0
    -- 1 = 0
    -- 2 = 1
    -- 3 = 2
    -- 4 = 3
    -- 5 = 4
    -- 6 = 5
    -- 7 = 6
    -- 8 = 7
    -- 9 = 8
    -- 10 = 9
    -- 11 = 10
    -- 12 = 11
    TimeSinceApo = 1,
    -- 将影响植物每天失去的水量以及它们避免疾病的能力。默认=正常
    -- 1 = 非常高
    -- 2 = 高
    -- 3 = 正常
    -- 4 = 低
    PlantResilience = 3,
    -- 控制植物收获时的产量。默认=正常
    -- 1 = 非常贫瘠
    -- 2 = 贫瘠
    -- 3 = 正常
    -- 4 = 丰富
    PlantAbundance = 3,
    -- 从执行动作中恢复疲劳的默认速度。默认=正常
    -- 1 = 非常快
    -- 2 = 快
    -- 3 = 正常
    -- 4 = 慢
    EndRegen = 3,
    -- 直升机通常经过事件区域的时间。默认=一次
    -- 1 = 从不
    -- 2 = 一次
    -- 3 = 有时
    Helicopter = 2,
    -- 僵尸吸引的元游戏事件发生的频率。默认=有时
    -- 1 = 从不
    -- 2 = 有时
    MetaEvent = 2,
    -- 控制玩家睡眠时的元游戏事件。默认=从不
    -- 1 = 从不
    -- 2 = 有时
    SleepingEvent = 1,
    -- 增加或减少地图上发电机生成的概率。默认=有时
    -- 1 = 极其稀有
    -- 2 = 稀有
    -- 3 = 有时
    -- 4 = 经常
    GeneratorSpawning = 3,
    -- 每小时消耗的燃料量。最小值=0.00最大值=100.00默认=1.00
    GeneratorFuelConsumption = 1.0,
    -- 增加或减少发现随机安全屋的概率。默认=稀有
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    SurvivorHouseChance = 3,
    -- 默认=稀有
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    VehicleStoryChance = 3,
    -- 默认=稀有
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    ZoneStoryChance = 3,
    -- 影响被搜刮的地图上注释标记的频率。默认=��时
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    AnnotatedMapChance = 4,
    -- 在角色创建时添加免费点数。最小值=-100 最大值=100 默认=0
    CharacterFreePoints = 0,
    -- 给予玩家建造的建筑额外的生命值，使其更能抵抗僵尸伤害。默认=正常
    -- 1 = 非常低
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    ConstructionBonusPoints = 3,
    -- 控制夜间环境光照。默认=正常
    -- 1 = 漆黑
    -- 2 = 黑暗
    -- 3 = 正常
    NightDarkness = 4,
    -- 控制从黄昏到黎明的时间。默认=正常
    -- 1 = 永夜
    -- 2 = 长
    -- 3 = 正常
    -- 4 = 短
    NightLength = 3,
    -- 增加和减少对身体的伤害，以及它们的愈合时间。默认=正常
    -- 1 = 低
    -- 2 = 正常
    InjurySeverity = 2,
    -- 启用或禁用幸存者在遭受冲击、僵尸伤害和跌落伤害时断肢。
    BoneFracture = true,
    -- 在僵尸尸体消失之前的时间。最小值=-1.00 最大值=2147483647.00 默认=216.00
    HoursForCorpseRemoval = 216.0,
    -- 控制附近腐烂的尸体对玩家健康和情绪的影响。默认=正常
    -- 1 = 无
    -- 2 = 低
    -- 3 = 正常
    DecayingCorpseHealthImpact = 3,
    -- 在地板和墙壁上喷洒多少血。默认=正常
    -- 1 = 无
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    BloodLevel = 3,
    -- 控制衣服如何褪色、变脏和沾血。默认=正常
    -- 1 = 禁用
    -- 2 = 慢
    -- 3 = 正常
    ClothingDegradation = 3,
    FireSpread = true,
    -- 在地图上移除腐烂食物的天数。-1表示腐烂食物不会被移除。最小值=-1 最大值=2147483647 默认=-1
    DaysForRottenFoodRemoval = -1,
    -- 如果启用，发电机会在室外瓷砖上工作，例如为燃气泵供电。
    AllowExteriorGenerator = true,
    -- 控制雾的最大强度。默认=正常
    -- 1 = 正常
    -- 2 = 中等
    MaxFogIntensity = 1,
    -- 控制雨的最大强度。默认=正常
    -- 1 = 正常
    -- 2 = 中等
    MaxRainFxIntensity = 1,
    -- 如果禁用，雪不会积聚在地面上，但仍会在植被和屋顶上可见。
    EnableSnowOnGround = true,
    -- 当启用时，某些近战武器能够一次击中多个僵尸。
    MultiHitZombies = true,
    -- 在僵尸攻击时被咬的概率。默认=高
    -- 1 = 低
    -- 2 = 中等
    RearVulnerability = 1,
    -- 禁用以在近战攻击时无障碍地行走。
    AttackBlockMovements = true,
    AllClothesUnlocked = false,
    -- 控制地图上发现的汽车的频率。默认=低
    -- 1 = 无
    -- 2 = 非常低
    -- 3 = 低
    -- 4 = 正常
    CarSpawnRate = 3,
    -- 控制发现的汽车中有多少汽油。默认=低
    -- 1 = 低
    -- 2 = 正常
    ChanceHasGas = 2,
    -- 控制发现的汽车中汽油罐的满度。默认=低
    -- 1 = 非常低
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    -- 5 = 非常高
    InitialGas = 2,
    -- 控制燃料站中汽油罐的满度。默认=正常
    -- 1 = 空
    -- 2 = 非常低
    -- 3 = 低
    -- 4 = 正常
    -- 5 = 高
    -- 6 = 非常高
    -- 7 = 满
    FuelStationGas = 4,
    -- 地图上车辆消耗的燃料量。最小值=0.00 最大值=100.00 默认=1.00
    CarGasConsumption = 1.0,
    -- 默认=稀有
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    LockedCar = 3,
    -- 地图上发现的汽车的总体状况。默认=低
    -- 1 = 非常低
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    CarGeneralCondition = 3,
    -- 控制对车辆造成的伤害。默认=正常
    -- 1 = 非常低
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    CarDamageOnImpact = 3,
    -- 玩家从汽车碰撞中受到的伤害。默认=无
    -- 1 = 无
    -- 2 = 低
    -- 3 = 正常
    -- 4 = 高
    DamageToPlayerFromHitByACar = 1,
    -- 启用或禁用地图上的交通堵塞。
    TrafficJam = true,
    -- 发现汽车时发出警报的频率。默认=极其稀有
    -- 1 = 从不
    -- 2 = 极其稀有
    -- 3 = 稀有
    -- 4 = 有时
    -- 5 = 经常
    CarAlarm = 2,
    -- 启用或禁用玩家因车祸受伤。
    PlayerDamageFromCrash = true,
    -- 在警笛关闭之前的天数。最小值=0.00 最大值=168.00 默认=0.00
    SirenShutoffHours = 0.0,
    --  控制玩家是否可以发现一辆被维护和照顾的汽车，在感染之后。默认=低
    -- 1 = 低
    -- 2 = 正常
    RecentlySurvivorVehicles = 1,
    -- 启用车辆生成。
    EnableVehicles = true,
    Map = {
        AllowMiniMap = true,
        AllowWorldMap = true,
        MapAllKnown = false,
    },
    ZombieLore = {
        -- 控制僵尸移动速度。默认=慢速行走者
        -- 1 = 奔跑者
        -- 2 = 快速行走者
        -- 3 = 慢速行走者
        Speed = 3,
        -- 控制僵尸每次攻击造成的伤害。默认=正常
        -- 1 = 超人
        -- 2 = 正常
        -- 3 = 虚弱
        Strength = 3,
        -- 控制杀死僵尸的难度。默认=正常
        -- 1 = 坚韧
        -- 2 = 正常
        -- 3 = 脆弱
        Toughness = 3,
        -- 控制僵尸病毒的传播。默认=血液+唾液
        -- 1 = 血液+唾液
        -- 2 = 仅唾液
        -- 3 = 所有人都被感染
        Transmission = 3,
        -- 控制感染效果的速度。默认=2-3天
        -- 1 = 立即
        -- 2 = 0-30秒
        -- 3 = 0-1分钟
        -- 4 = 0-12小时
        -- 5 = 2-3天
        -- 6 = 1-2周
        Mortality = 5,
        -- 控制僵尸尸体复活的速度。默认=0-1分钟
        -- 1 = 立即
        -- 2 = 0-30秒
        -- 3 = 0-1分钟
        -- 4 = 0-12小时
        -- 5 = 2-3天
        Reanimate = 3,
        -- 控制僵尸的智力。默认=基础导航
        -- 1 = 可导航+使用门
        -- 2 = 可导航
        -- 3 = 基础导航
        Cognition = 3,
        -- 控制僵尸可以在车辆下爬行的频率。默认=经常
        -- 1 = 仅爬行者
        -- 2 = 极其稀有
        -- 3 = 稀有
        -- 4 = 有时
        -- 5 = 经常
        -- 6 = 非常频繁
        CrawlUnderVehicle = 2,
        -- 控制僵尸记住玩家的时间。默认=正常
        -- 1 = 长
        -- 2 = 正常
        -- 3 = 短
        Memory = 3,
        -- 控制僵尸分解的效果。默认=减速+虚弱化
        -- 1 = 减速+虚弱化
        -- 2 = 仅减速
        -- 3 = 仅虚弱化
        Decomp = 1,
        -- 控制僵尸的视野范围。默认=正常
        -- 1 = 鹰眼
        -- 2 = 正常
        Sight = 2,
        -- 控制僵尸的听力范围。默认=正常
        -- 1 = 精确
        -- 2 = 正常
        Hearing = 2,
        -- 僵尸在没有看到/听到玩家的情况下是否可以攻击门和建筑物
        ThumpNoChasing = true,
        -- 控制僵尸是否可以破坏玩家建造的建筑和防御设施
        ThumpOnConstruction = true,
        -- 控制僵尸活动时间。活跃的僵尸将使用"速度"设置中的速度，不活跃的僵尸将更慢且不会追逐。默认=全天
        -- 1 = 全天
        -- 2 = 仅夜间
        ActiveOnly = 1,
        -- 僵尸破坏窗户和门时是否会触发房屋警报
        TriggerHouseAlarm = false,
        -- 僵尸在翻越围栏后是否有机会扑向玩家
        ZombiesFenceLunge = true,
    },
    ZombieConfig = {
        -- 由“僵尸数量”人口选项设置。4.0 = Insane, Very High = 3.0, 2.0 = High, 1.0 = Normal, 0.35 = Low, 0.0 = None. Minimum=0.00 Maximum=4.00 Default=1.00
        PopulationMultiplier = 0.75,
        -- 调整游戏开始时的预期人口。Minimum=0.00 Maximum=4.00 Default=1.00
        PopulationStartMultiplier = 0.3,
        -- 调整峰值日的人口预期。Minimum=0.00 Maximum=4.00 Default=1.50
        PopulationPeakMultiplier = 1.2,
        -- 人口达到峰值的天数。Minimum=1 Maximum=365 Default=28
        PopulationPeakDay = 14,
        -- 必须经过多少小时才能在细胞中重新生成僵尸。如果为零，则禁用生成。Minimum=0.00 Maximum=8760.00 Default=72.00
        RespawnHours = 96.0,
        -- 必须经过多少小时才能在细胞中重新生成僵尸。Minimum=0.00 Maximum=8760.00 Default=16.00
        RespawnUnseenHours = 16.0,
        -- 细胞中可能重新生成的细胞中所需人口的分数。Minimum=0.00 Maximum=1.00 Default=0.10
        RespawnMultiplier = 0.4,
        -- 必须经过多少小时才能将僵尸迁移到细胞的空部分。如果为零，则禁用迁移。Minimum=0.00 Maximum=8760.00 Default=12.00
        RedistributeHours = 12.0,
        -- 僵尸将尝试走近它听到的最后一个声音的距离。Minimum=10 Maximum=1000 Default=100
        FollowSoundDistance = 100,
        -- 僵尸群在空闲时形成的群大小。零表示僵尸不形成群。僵尸不会在建筑物或森林区域形成群。Minimum=0 Maximum=1000 Default=20
        RallyGroupSize = 10,
        -- 僵尸群在空闲时移动的距离。Minimum=5 Maximum=50 Default=20
        RallyTravelDistance = 10,
        -- 僵尸群之间的距离。Minimum=5 Maximum=25 Default=15
        RallyGroupSeparation = 15,
        -- 群成员与群领导保持的距离。Minimum=1 Maximum=10 Default=3
        RallyGroupRadius = 3,
    },
  }